apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kube-opencti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2.5
        volumeMounts:
        - name: redisdata
          mountPath: /data
      volumes:
        - name: redisdata
          persistentVolumeClaim:
            claimName: redis-pvc
