apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: kube-opencti
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
