apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: lab-opencti
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
