apiVersion: v1
kind: Service
metadata:
  name: opencti
  namespace: kube-opencti
spec:
  type: LoadBalancer
  selector:
    app: opencti
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
