apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencti-connector-export-file-csv
  namespace: kube-opencti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencti-connector-export-file-csv
  template:
    metadata:
      labels:
        app: opencti-connector-export-file-csv
    spec:
      containers:
        - name: opencti-connector-export-file-csv
          image: opencti/connector-export-file-csv:6.2.1
          env:
            - name: OPENCTI_URL
              value: "http://opencti:8080"
            - name: OPENCTI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: opencti-secrets
                  key: opencti-admin-token
            - name: CONNECTOR_ID
              value: "a7c40083-eaf5-4658-95e7-ef6c3c1bd3b6"
            - name: CONNECTOR_TYPE
              value: "INTERNAL_EXPORT_FILE"
            - name: CONNECTOR_NAME
              value: "ExportFileCsv"
            - name: CONNECTOR_SCOPE
              value: "text/plain"
            - name: CONNECTOR_LOG_LEVEL
              value: "error"
